version: '3.6'

services:
  ebox-api:
    build:
      context: .
      args:
        target: production
    ports:
      - 4000:4000
    links:
      - database
    environment:
      DB_HOST: localhost
      DB_PORT: 5434
      DB_USER: postgres
      DB_PASSWORD: supersecret
      DB_NAME: postgres

  database:
    image: postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: supersecret

  postgres-admin:
    image: dpage/pgadmin4
    ports:
      - '4010:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'asd@qwe.pl'
      PGADMIN_DEFAULT_PASSWORD: 'asdqwe'
    links:
      - database